<?php include __DIR__ . '/../header.html' ?>
    <div class="container">
        <div class="row">
            <h3>Adicionar Categorias</h3>
            <h5>Post - <?php echo $post->getTitle(); ?></h5>
            <form name="form" method="post" action="/posts/<?php echo $post->getId(); ?>/set-categories">
                <div class="form-group">
                    <label for="Categories">Categorias</label>
                    <select class="form-control" name="categories[]" multiple>
                        <?php foreach ($categories as $category): ?>
                            <option value="<?php echo $category->getId() ?>">
                                <?php echo $category->getName() ?>
                            </option>
                        <?php endforeach; ?>
                    </select>
                </div>
                <button type="submit" class="btn btn-default">Salvar</button>
            </form>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html' ?>