<?php include __DIR__ . '/../header.html' ?>
<div class="container">
    <div class="row">
        <h3>Novo Post</h3>
        <form name="form" method="post" action="/posts/store">
            <div class="form-group">
                <label for="title">Título</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Digite o título">
            </div>
            <div class="form-group">
                <label for="content">Conteúdo</label>
                <textarea id="content" name="content" class="form-control"></textarea>
            </div>
            <button type="submit" class="btn btn-default">Enviar</button>
        </form>
    </div>
</div>
<?php include __DIR__ . '/../footer.html' ?>
