<?php include __DIR__ . '/../header.html' ?>
    <div class="container">
        <div class="row">
            <h3>Editar categoria</h3>
            <form name="form" method="post" action="/posts/<?php echo $post->getId(); ?>/update">
                <div class="form-group">
                    <label for="name">Título</label>
                    <input type="text" class="form-control" id="title"
                           name="title" placeholder="Digite o título" value="<?php echo $post->getTitle();?>">
                </div>
                <div class="form-group">
                <label for="content">Conteúdo</label>
                <textarea id="content" name="content" class="form-control">
                    <?php echo $post->getContent();?>
                </textarea>
            </div>
                <button type="submit" class="btn btn-default">Atualizar</button>
            </form>
        </div>
    </div>
<?php include __DIR__ . '/../footer.html' ?>