<?php include __DIR__ . '/../header.html';?>

<div class="container">
    <div class="row">
        <h3>Listagem de Categorias</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    
                </tr>
            </tbody>
        </table>
    </div>
</div>

<?phpinclude __DIR__ . '/../footer.html'; ?>
