<?php include __DIR__ . '/../header.html'; ?>

<div class="container">
    <div class="row">
        <h3>Listagem de Categorias</h3>
        <a class="btn btn-success" href="/categories/create">Nova Categoria</a>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Nome</th>
                    <th>Açoes</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($categories as $category): ?>
                    <tr>
                        <td><?php echo $category->getId(); ?></td>
                        <td><?php echo $category->getName(); ?></td>
                        <td>
                            <a href="/categories/<?php echo $category->getId(); ?>/edit" class="btn btn-default">Editar</a>
                            <a href="/categories/<?php echo $category->getId(); ?>/remove" class="btn btn-danger">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php include __DIR__ . '/../footer.html'; ?>
